version: 1.0
Resources:
- TargetService:
    Type: AWS::ECS::Service
    Properties:
      TaskDefinition: "arn:aws:iam::$AWS_ACCOUNT_ID:role/ecsTaskExecutionRole/strapi-task:${{ steps.build.outputs.revision }}"
      LoadBalancerInfo:
        ContainerName: "strapi"
        ContainerPort: 1337 >>appspec.yaml
      Cluster: "strapi-cluster-bhr"
      ServiceName: "strapi-service"
      DesiredCount: 1
      LaunchType: "FARGATE"
      NetworkConfiguration:
        AwsvpcConfiguration:
          Subnets:
          - "subnet-aws_subnet.public1.id" # Replace with your subnet ID
          - "subnet-aws_subnet.public2.id" # Replace with your subnet ID
          SecurityGroups:
          - "sg-xxxxx" # Replace with your security group ID
          AssignPublicIp: ENABLED
