version: 1
Resources:
- TargetService:
    Type: AWS::ECS::Service
    Properties:
      TaskDefinition: strapi-task:182
      LoadBalancerInfo:
        ContainerName: strapi
        ContainerPort: 1337
