version: 1.0
Resources:
- TargetService:
    Type: AWS::ECS::Service
    Properties:
      TaskDefinition: arn:aws:ecs:us-east-2:607700977843:task-definition/strapi-task:183
      LoadBalancerInfo:
        ContainerName: "strapi"
        ContainerPort: 1337
