name: Deploy Strapi to ECS via CodeDeploy

on:
  push:
    branches: [main]

env:
  AWS_REGION: us-east-2
  ECR_REPOSITORY: projects-bhr
  ECS_CLUSTER: strapi-cluster
  ECS_SERVICE: strapi-service
  TASK_DEF_FAMILY: strapi-task
  CODE_DEPLOY_APP: strapi-codedeploy-app
  DEPLOYMENT_GROUP: strapi-deployment-group

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout source
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build, Tag, and Push Docker Image
      env:
        IMAGE_TAG: ${{ github.sha }}
      run: |
        IMAGE_URI=${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:$IMAGE_TAG
        docker build -t $IMAGE_URI .
        docker push $IMAGE_URI
        echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV

    - name: Render new ECS Task Definition with new image
      id: render-taskdef
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: ecs-task-def.json
        container-name: strapi
        image: ${{ env.IMAGE_URI }}

    - name: Register new ECS Task Definition
      id: register-taskdef
      uses: aws-actions/amazon-ecs-register-task-definition@v1
      with:
        task-definition: ${{ steps.render-taskdef.outputs.task-definition }}

    - name: Create CodeDeploy Deployment
      id: codedeploy
      run: |
        aws deploy create-deployment \
          --application-name strapi-app \
          --deployment-group-name ${{ env.DEPLOYMENT_GROUP }} \
          --revision revisionType=AppSpecContent,appSpecContent={"content":"version: 1.0\nResources:\n  - TargetService:\n      Type: AWS::ECS::Service\n      Properties:\n        TaskDefinition: ${{ steps.register-taskdef.outputs.task-definition-arn }}\n        LoadBalancerInfo:\n          ContainerName: \"strapi\"\n          ContainerPort: 1337"} \
          --deployment-config-name CodeDeployDefault.ECSAllAtOnce \
          --region us-east-2

    - name: (Optional) Monitor Deployment Status
      run: |
        echo "Deployment created: ${{ steps.codedeploy.outputs.deployment-id }}"
        # Optional: use describe-deployment + polling here for prod monitoring
